// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type State struct {
	StateID     int32     `json:"state_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Slug        string    `json:"slug"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Sublocation struct {
	SublocationID int32     `json:"sublocation_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	StateID       int32     `json:"state_id"`
	Slug          string    `json:"slug"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Video struct {
	VideoID       int32     `json:"video_id"`
	Title         string    `json:"title"`
	Src           string    `json:"src"`
	Type          string    `json:"type"`
	StateID       int32     `json:"state_id"`
	SublocationID *int32    `json:"sublocation_id"`
	Status        string    `json:"status"`
	CreatedBy     string    `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
