// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sublocations.sql

package db

import (
	"context"
	"time"
)

const createSublocation = `-- name: CreateSublocation :one
INSERT INTO sublocations (name, description, state_id)
VALUES ($1, $2, $3)
RETURNING sublocation_id, name, description, state_id, slug, created_at, updated_at
`

type CreateSublocationParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	StateID     int32  `json:"state_id"`
}

func (q *Queries) CreateSublocation(ctx context.Context, arg CreateSublocationParams) (Sublocation, error) {
	row := q.db.QueryRow(ctx, createSublocation, arg.Name, arg.Description, arg.StateID)
	var i Sublocation
	err := row.Scan(
		&i.SublocationID,
		&i.Name,
		&i.Description,
		&i.StateID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSublocationByID = `-- name: GetSublocationByID :one
SELECT sub.sublocation_id, sub.name, sub.description, sub.state_id, sub.slug,
       sub.created_at, sub.updated_at,
       s.name AS state_name,
       COUNT(v.video_id)::int AS video_count
FROM sublocations sub
JOIN states s ON s.state_id = sub.state_id
LEFT JOIN videos v ON v.sublocation_id = sub.sublocation_id AND v.status = 'active'
WHERE sub.sublocation_id = $1
GROUP BY sub.sublocation_id, s.name
`

type GetSublocationByIDRow struct {
	SublocationID int32     `json:"sublocation_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	StateID       int32     `json:"state_id"`
	Slug          string    `json:"slug"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	StateName     string    `json:"state_name"`
	VideoCount    int32     `json:"video_count"`
}

func (q *Queries) GetSublocationByID(ctx context.Context, sublocationID int32) (GetSublocationByIDRow, error) {
	row := q.db.QueryRow(ctx, getSublocationByID, sublocationID)
	var i GetSublocationByIDRow
	err := row.Scan(
		&i.SublocationID,
		&i.Name,
		&i.Description,
		&i.StateID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateName,
		&i.VideoCount,
	)
	return i, err
}

const getSublocationBySlug = `-- name: GetSublocationBySlug :one
SELECT sub.sublocation_id, sub.name, sub.description, sub.state_id, sub.slug,
       sub.created_at, sub.updated_at,
       s.name AS state_name,
       COUNT(v.video_id)::int AS video_count
FROM sublocations sub
JOIN states s ON s.state_id = sub.state_id
LEFT JOIN videos v ON v.sublocation_id = sub.sublocation_id AND v.status = 'active'
WHERE sub.slug = $1
GROUP BY sub.sublocation_id, s.name
`

type GetSublocationBySlugRow struct {
	SublocationID int32     `json:"sublocation_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	StateID       int32     `json:"state_id"`
	Slug          string    `json:"slug"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	StateName     string    `json:"state_name"`
	VideoCount    int32     `json:"video_count"`
}

func (q *Queries) GetSublocationBySlug(ctx context.Context, slug string) (GetSublocationBySlugRow, error) {
	row := q.db.QueryRow(ctx, getSublocationBySlug, slug)
	var i GetSublocationBySlugRow
	err := row.Scan(
		&i.SublocationID,
		&i.Name,
		&i.Description,
		&i.StateID,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateName,
		&i.VideoCount,
	)
	return i, err
}

const listSublocationsByState = `-- name: ListSublocationsByState :many
SELECT sub.sublocation_id, sub.name, sub.description, sub.state_id, sub.slug,
       sub.created_at, sub.updated_at,
       s.name AS state_name,
       COUNT(v.video_id)::int AS video_count
FROM sublocations sub
JOIN states s ON s.state_id = sub.state_id
LEFT JOIN videos v ON v.sublocation_id = sub.sublocation_id AND v.status = 'active'
WHERE sub.state_id = $1
GROUP BY sub.sublocation_id, s.name
ORDER BY sub.name
`

type ListSublocationsByStateRow struct {
	SublocationID int32     `json:"sublocation_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	StateID       int32     `json:"state_id"`
	Slug          string    `json:"slug"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	StateName     string    `json:"state_name"`
	VideoCount    int32     `json:"video_count"`
}

func (q *Queries) ListSublocationsByState(ctx context.Context, stateID int32) ([]ListSublocationsByStateRow, error) {
	rows, err := q.db.Query(ctx, listSublocationsByState, stateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSublocationsByStateRow{}
	for rows.Next() {
		var i ListSublocationsByStateRow
		if err := rows.Scan(
			&i.SublocationID,
			&i.Name,
			&i.Description,
			&i.StateID,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.VideoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
