/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsSlugRouteImport } from './routes/locations/$slug'
import { Route as LocationsSlugSublocationSlugRouteImport } from './routes/locations/$slug.$sublocationSlug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugSublocationSlugRoute =
  LocationsSlugSublocationSlugRouteImport.update({
    id: '/$sublocationSlug',
    path: '/$sublocationSlug',
    getParentRoute: () => LocationsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/locations/$slug': typeof LocationsSlugRouteWithChildren
  '/locations/': typeof LocationsIndexRoute
  '/locations/$slug/$sublocationSlug': typeof LocationsSlugSublocationSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/locations/$slug': typeof LocationsSlugRouteWithChildren
  '/locations': typeof LocationsIndexRoute
  '/locations/$slug/$sublocationSlug': typeof LocationsSlugSublocationSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/locations/$slug': typeof LocationsSlugRouteWithChildren
  '/locations/': typeof LocationsIndexRoute
  '/locations/$slug/$sublocationSlug': typeof LocationsSlugSublocationSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/locations/$slug'
    | '/locations/'
    | '/locations/$slug/$sublocationSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/locations/$slug'
    | '/locations'
    | '/locations/$slug/$sublocationSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/locations/$slug'
    | '/locations/'
    | '/locations/$slug/$sublocationSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CallbackRoute: typeof CallbackRoute
  ContactRoute: typeof ContactRoute
  LocationsSlugRoute: typeof LocationsSlugRouteWithChildren
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/$sublocationSlug': {
      id: '/locations/$slug/$sublocationSlug'
      path: '/$sublocationSlug'
      fullPath: '/locations/$slug/$sublocationSlug'
      preLoaderRoute: typeof LocationsSlugSublocationSlugRouteImport
      parentRoute: typeof LocationsSlugRoute
    }
  }
}

interface LocationsSlugRouteChildren {
  LocationsSlugSublocationSlugRoute: typeof LocationsSlugSublocationSlugRoute
}

const LocationsSlugRouteChildren: LocationsSlugRouteChildren = {
  LocationsSlugSublocationSlugRoute: LocationsSlugSublocationSlugRoute,
}

const LocationsSlugRouteWithChildren = LocationsSlugRoute._addFileChildren(
  LocationsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CallbackRoute: CallbackRoute,
  ContactRoute: ContactRoute,
  LocationsSlugRoute: LocationsSlugRouteWithChildren,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
