/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsSlugIndexRouteImport } from './routes/locations/$slug.index'
import { Route as LocationsSlugSublocationSlugRouteImport } from './routes/locations/$slug.$sublocationSlug'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugIndexRoute = LocationsSlugIndexRouteImport.update({
  id: '/locations/$slug/',
  path: '/locations/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugSublocationSlugRoute =
  LocationsSlugSublocationSlugRouteImport.update({
    id: '/locations/$slug/$sublocationSlug',
    path: '/locations/$slug/$sublocationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/locations/': typeof LocationsIndexRoute
  '/locations/$slug/$sublocationSlug': typeof LocationsSlugSublocationSlugRoute
  '/locations/$slug/': typeof LocationsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/locations': typeof LocationsIndexRoute
  '/locations/$slug/$sublocationSlug': typeof LocationsSlugSublocationSlugRoute
  '/locations/$slug': typeof LocationsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/locations/': typeof LocationsIndexRoute
  '/locations/$slug/$sublocationSlug': typeof LocationsSlugSublocationSlugRoute
  '/locations/$slug/': typeof LocationsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/dashboard'
    | '/locations/'
    | '/locations/$slug/$sublocationSlug'
    | '/locations/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/dashboard'
    | '/locations'
    | '/locations/$slug/$sublocationSlug'
    | '/locations/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/dashboard'
    | '/locations/'
    | '/locations/$slug/$sublocationSlug'
    | '/locations/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CallbackRoute: typeof CallbackRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  LocationsSlugSublocationSlugRoute: typeof LocationsSlugSublocationSlugRoute
  LocationsSlugIndexRoute: typeof LocationsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/': {
      id: '/locations/$slug/'
      path: '/locations/$slug'
      fullPath: '/locations/$slug/'
      preLoaderRoute: typeof LocationsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/$sublocationSlug': {
      id: '/locations/$slug/$sublocationSlug'
      path: '/locations/$slug/$sublocationSlug'
      fullPath: '/locations/$slug/$sublocationSlug'
      preLoaderRoute: typeof LocationsSlugSublocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CallbackRoute: CallbackRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  LocationsSlugSublocationSlugRoute: LocationsSlugSublocationSlugRoute,
  LocationsSlugIndexRoute: LocationsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
